name: Android CI - Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Build web assets (Vite)
        run: npm run build

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK (minimal)
        uses: r0adkll/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'
          cmake: false
          ndk: ''

      - name: Ensure libs directory and local smbj jar (fallback to download)
        run: |
          mkdir -p android/app/libs
          if [ -f android/app/libs/smbj-0.14.0.jar ]; then
            echo "Local smbj jar already present"
            ls -la android/app/libs/smbj-0.14.0.jar
          else
            echo "Local smbj jar missing, attempting download from Maven Central / JitPack"
            set -e
            URLS=(
              "https://repo1.maven.org/maven2/com/hierynomus/smbj/0.14.0/smbj-0.14.0.jar"
              "https://jitpack.io/com/hierynomus/smbj/0.14.0/smbj-0.14.0.jar"
            )
            for u in "${URLS[@]}"; do
              echo "Trying $u"
              curl -fsS --retry 3 -o android/app/libs/smbj-0.14.0.jar "$u" && echo "Downloaded from $u" && break || echo "Failed $u"
            done
            if [ -f android/app/libs/smbj-0.14.0.jar ]; then ls -la android/app/libs; else echo "Could not download smbj jar; proceeding without local jar (Gradle may resolve via repositories)"; fi
          fi

      - name: Copy web assets to native project
        run: npx cap copy

      - name: Grant execute for gradlew
        run: chmod +x ./android/gradlew

      - name: Build APK (Gradle)
        working-directory: android
        run: ./gradlew clean :app:assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
